import Image from "next/image";

export function CarouselSlide() {
  return (
    <div className="flex w-full h-full overflow-hidden p-6 lg:p-12 lg:mt-[100px] lg:mb-20">
      <div className="animate-slideCarousel flex gap-32 whitespace-nowrap p-4">
        <Image
          src="/Definicao.svg"
          width={308}
          height={300}
          quality={100}
          alt=""
        />
        <Image
          src="/Performance.svg"
          width={450}
          height={300}
          quality={100}
          alt=""
        />
        <Image
          src="/Saude.svg"
          width={300}
          height={300}
          quality={100}
          alt=""
        />
        <Image
          src="/Definicao.svg"
          width={308}
          height={300}
          quality={100}
          alt=""
        />
         <Image
          src="/Saude.svg"
          width={308}
          height={300}
          quality={100}
          alt=""
        />
        <Image
          src="/Performance.svg"
          width={450}
          height={300}
          quality={100}
          alt=""
        />
        <Image
          src="/Emagrecimento.svg"
          width={650}
          height={300}
          quality={100} 
          alt=""
        />
        <Image
          src="/Definicao.svg"
          width={308}
          height={300}
          quality={100}
          alt=""
        />
         <Image
          src="/Saude.svg"
          width={308}
          height={300}
          quality={100}
          alt=""
        />
        <Image
          src="/Performance.svg"
          width={450}
          height={300}
          quality={100}
          alt=""
        />
        <Image
          src="/Saude.svg"
          width={300}
          height={300}
          quality={100}
          alt=""
        />
        <Image
          src="/Definicao.svg"
          width={308}
          height={300}
          quality={100}
          alt=""
        />
        <Image
          src="/Emagrecimento.svg"
          width={450}
          height={300}
          quality={100}
          alt=""
        />
        <Image
          src="/Saude.svg"
          width={300}
          height={300}
          quality={100}
          alt=""
        />
        <Image
          src="/Definicao.svg"
          width={308}
          height={300}
          quality={100}
          alt=""
        />
        <Image
          src="/Emagrecimento.svg"
          width={308}
          height={300}
          quality={100}
          alt=""
        />
      </div>
    </div>
  );
}